<a href="https://colab.research.google.com/github/anishah2505-star/solar_power_output_predicter/blob/main/solarpower_output_predicter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import joblib

In [5]:
df=pd.read_csv("/solar_power_output.csv")
df.head()
df.tail()
df.describe()
df.isnull()

     temperature  humidity  solar_irradiance  wind_speed  solar_power_output
0          False     False             False       False               False
1          False     False             False       False               False
2          False     False             False       False               False
3          False     False             False       False               False
4          False     False             False       False               False
..           ...       ...               ...         ...                 ...
495        False     False             False       False               False
496        False     False             False       False               False
497        False     False             False       False               False
498        False     False             False       False               False
499        False     False             False       False               False

[500 rows x 5 columns]

In [6]:
x=df[['temperature','humidity','solar_irradiance','wind_speed']]
y=df['solar_power_output']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.8,random_state=42)
x_test

     temperature   humidity  solar_irradiance  wind_speed
361    26.082205  56.263107        289.595970    6.561618
73     30.386536  69.766936        116.086541    8.627971
374    11.779716  22.030908        322.507967    7.328015
155    16.051382  30.206424        777.444976    9.369578
104    32.689162  29.650870        995.417040    0.694238
..           ...        ...               ...         ...
434    12.102670  33.734343        225.686129    6.764679
430    13.574792  31.148486        509.265870    5.799838
337    27.591446  48.991512        712.205418    3.382675
236    17.019309  51.395609        877.922425    4.497846
207    26.587544  84.789956        501.312436    2.160382

[400 rows x 4 columns]

In [8]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [9]:
y_pred=model.predict(x_test)
y_pred

array([144.99863719,  57.98296492, 163.10541143, 391.51123798,
       498.65781288, 200.88499148, 280.96215297, 343.6359455 ,
       208.09665144, 272.26785286, 270.15691504,  70.90365366,
       430.39146686, 476.50962383, 130.8671421 , 489.17409875,
       352.75938618,  64.3525589 , 285.95956893, 313.9981004 ,
       156.12638469, 216.13933977, 326.43153141, 458.07767762,
       222.79312375, 342.64502773, 258.49432363, 251.5188633 ,
       487.05969766, 490.00916275, 352.82185513, 136.91406112,
       486.55773316, 167.21665513, 442.75219519, 500.7434775 ,
       440.54657942, 183.28258751, 499.013379  , 238.94178471,
       343.75323619, 280.17581124, 213.65989987, 473.15266707,
       102.99224466, 354.7751346 , 132.13516633, 496.11347578,
       472.86417412, 464.35579855,  69.15792595, 336.52385909,
       271.16976946, 141.27057137, 329.53803831, 207.25158282,
       432.80849768, 460.01392366, 271.28045115, 148.06952561,
       322.84070636, 189.06647521, 149.28207591,  53.39854902,
       478.96110739, 192.982735  , 326.80483868, 156.61304062,
       486.19220836,  80.8611712 , 249.34306655, 257.30280228,
       493.69632498, 228.59574926, 380.51058608, 369.25200705,
       320.29959197, 179.47902132, 471.09568898,  71.76178699,
       327.74993462, 237.9975522 , 394.79853798, 336.99596294,
       122.09994989, 476.53255127, 482.32961897, 288.73746321,
       297.02338423, 112.1750564 , 226.25673462, 444.22001384,
       329.47827015, 490.14578805, 281.02983754, 213.9896957 ,
       328.29102617, 239.68267008, 141.82174891, 467.18239763,
       326.26565452, 350.35956801,  66.97581503, 443.74171873,
       153.7820717 , 397.08022124, 473.77998745, 235.60872786,
       374.42962251,  86.15761347, 272.80442506, 114.744254  ,
       343.41000827, 262.84645223, 501.48021651, 367.25449344,
        63.26517407, 260.74727626, 446.50497522, 194.18670646,
       475.94402436, 401.58456181, 158.91511357, 354.99598001,
       152.26936071, 173.31235381, 102.97138072, 196.79586173,
        87.93739275, 273.67877761, 316.81532435, 292.76957801,
       303.17156272, 437.12921748, 423.49487649, 232.07163985,
       205.20196421, 474.21711721, 305.60669515,  81.304005  ,
       157.80027629, 173.85911051, 246.48069643, 152.64612565,
       105.61186173, 226.19198798, 485.21387119, 245.33350154,
       411.0408788 ,  52.56480664, 347.48009412,  93.60124012,
       327.7738408 , 131.5770465 ,  99.31139354, 239.64413405,
       378.23684183, 347.43836806, 261.37991816, 442.45758007,
       420.17761694,  87.97636503, 337.62290029, 422.08551547,
       366.83344183, 382.05418481, 438.01238961, 431.6079541 ,
       306.09386691, 362.61967173, 377.71681115, 446.91352708,
       251.38717923, 168.31728464, 315.13676901, 290.63271097,
       272.79478139, 205.66185196, 169.98904841, 155.37693944,
       154.04937301, 441.03437699, 349.80920309,  97.39527982,
        64.54246792, 207.78067047, 109.6127115 ,  98.33555678,
       239.75420654,  52.10424348,  80.89202325, 443.62151247,
       125.76603733, 403.81202511, 118.0373187 , 464.29723005,
       445.02395679, 323.79524068, 363.02951392, 459.93503511,
       233.40098809, 446.57643521, 330.55578272, 420.80414661,
       385.82980878, 108.27241978, 495.47437345, 493.07546659,
       410.55891104, 175.0550958 , 410.2396524 , 107.4771126 ,
        84.09983117, 365.17036263, 243.28243359, 271.04351298,
       370.65048008, 334.9741656 , 376.05384978, 342.83036396,
       488.99622575, 265.87731853, 200.48455566, 488.20991661,
       318.42415073, 382.00080334, 393.38546261, 351.68648788,
        88.9959465 , 333.12973257, 149.81347819, 155.69485282,
       189.25594715, 360.35800659, 460.82440878, 205.91839058,
        82.7378594 , 441.91799069, 369.34786066,  97.63097459,
       283.52281183,  92.90666581, 357.02386278, 149.43530387,
       124.46868914, 469.13402077,  87.62420749,  78.1259948 ,
       251.04326631, 280.65752734, 401.33821689, 123.97428519,
       198.04001296, 390.28435104,  94.97740213,  68.7784186 ,
       407.88098333, 125.48888219, 346.73178451, 425.23176413,
       208.22153879, 415.87568714, 127.96647361, 147.57185122,
       305.5400912 , 133.13204284, 353.06985376, 133.43530527,
       413.00679484, 439.00788299, 470.35235428,  59.23592115,
       107.58994117, 442.44199914, 334.68560787, 310.53725685,
       396.43690509, 425.24400395, 198.24309823, 298.89415464,
        72.06078458, 473.19225894, 252.17952956, 171.15899943,
       167.28203822, 191.26241073,  83.19488172, 443.07908042,
       249.83585693, 109.38636057, 443.99641379, 411.02043104,
       244.93444151, 166.9940435 , 150.04575493, 292.69768812,
       408.69733937, 268.37141878, 363.35586302, 103.43661198,
        66.81998585,  63.03492823, 452.55413139, 124.51597019,
       433.09914969, 485.41725976,  75.77219272, 144.95940491,
       310.15608918, 451.56837518,  67.46602574, 238.92006507,
        67.69713961, 159.22112893, 232.94190944, 282.43185018,
       101.79220665, 392.91483787, 488.96046776, 199.96783796,
       149.30770224, 442.90275414, 449.96134089, 227.4076237 ,
       381.6774684 ,  54.50322014, 260.13896043, 397.21024473,
       360.76169882, 168.04617472,  62.13482517, 475.17942038,
       360.99702817, 195.77349961, 328.64470392, 356.41650363,
       329.27546713, 442.10005813, 117.5880603 , 129.26019761,
       287.1034603 , 442.51059361, 193.97106946, 212.66687524,
       390.30767932, 404.72032899, 217.98224912, 276.98718145,
       358.61587091, 302.64362343, 361.24466553, 172.07269749,
       412.24098435, 140.73550811, 473.78900751,  75.59979864,
       230.20146573, 440.60471518, 408.16356713, 491.62505597,
       401.00165892, 305.55072295, 148.652624  , 493.71883603,
        59.80676332, 151.76469769, 264.53155661, 407.60003729,
       392.73927584, 363.19672259, 430.77891733, 495.57213421,
       453.61636909, 171.85811787,  63.14339533, 201.3447717 ,
       485.53131352, 268.35061458, 398.23627649,  83.04545926,
       217.92562621, 412.79006634, 160.66135117, 130.78722459,
       346.31437444, 240.8302152 ,  63.90656112, 368.47515658,
       121.84186927, 291.60992639, 318.04209915, 441.5382757 ,
       380.18104229,  83.99220648, 274.96859246, 113.86452749,
       255.95774606, 356.42360766, 439.61514911, 248.68456837])

In [10]:
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(f"mean squared error:{mse}")
print(f"R-squared:{r2}")

mean squared error:25.723868990361865
R-squared:0.9985581338344286

In [11]:
joblib.dump(model,'solar_power_prediction_model.pkl')

['solar_power_prediction_model.pkl']

In [12]:
model=joblib.load("solar_power_prediction_model.pkl")
new_data=np.array([[19.36,75.85,266.61,5.19]])
predicted_output=model.predict(new_data)
print(f"predicted solar power output:{predicted_output[0]}watts")

predicted solar power output:132.1302021871001watts

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(